apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customization
  namespace: ext
data:
  MIN_RANDOM_DELAY: "{{ .Values.min_random_delay }}"
  MAX_RANDOM_DELAY: "{{ .Values.max_random_delay }}"
  LAGSPIKE_PERCENTAGE: "{{ .Values.lagspike_percentage }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: ext
  labels:
    app: ext
    tier: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: ext
    tier: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-priv
  namespace: ext
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext
    tier: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: ext
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ext
      tier: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
         app: ext
         tier: {{ .Values.name }}
    spec:
      serviceAccountName: no-priv
      automountServiceAccountToken: false
#      securityContext:
#        runAsUser: 10000
#        runAsGroup: 20000
#        fsGroup: 30000
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.registry }}/extpayment-{{ .Values.tech }}:{{ .Values.version }}
        imagePullPolicy: Always
#        securityContext:
#          runAsUser: 10001
#          allowPrivilegeEscalation: false
        volumeMounts:
        - name: customization
          mountPath: /etc/customization
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        startupProbe:
          periodSeconds: 5
          failureThreshold: 40
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 4
          httpGet:
            path: /healthz
            port: http
#        resources:
#          requests:
#            cpu: 250m
#            memory: 32Mi
#          limits:
#            memory: 32Mi
      volumes:
      - name: customization
        configMap:
          name: customization