apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customization
  namespace: {{ .Values.namespace }}
data:
  MIN_RANDOM: "{{ .Values.min_delay }}"
  MAX_RANDOM: "{{ .Values.max_delay }}"
  JOB_MIN: "{{ .Values.job_min_delay }}"
  JOB_MAX: "{{ .Values.job_max_delay }}"
  PRODUCTION_SVC: "{{ .Values.production_svc }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: factory
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: factory
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:      ['batch']
  resources:      ['jobs']
  verbs:          ['create']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: factory
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: factory
subjects:
- kind: ServiceAccount
  name: factory
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    tier: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    tier: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        tier: {{ .Values.name }}
    spec:
      serviceAccountName: factory
#      securityContext:
#        runAsUser: 10000
#        runAsGroup: 20000
#        fsGroup: 30000
      containers:
      - name: order
        image: {{ .Values.registry }}/extprod-{{ .Values.tech }}:{{ .Values.version }}
        imagePullPolicy: Always
#        securityContext:
#          runAsUser: 10001
#          allowPrivilegeEscalation: false
        volumeMounts:
        - name: customization
          mountPath: /etc/customization
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
#        - name: https
#          containerPort: 443
#          protocol: TCP
        startupProbe:
          periodSeconds: 5
          failureThreshold: 40
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 4
          httpGet:
            path: /healthz
            port: http
      volumes:
      - name: customization
        configMap:
          name: customization