apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-{{ .Values.payment_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname }}
    tier: {{ .Values.payment_name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appname }}
    tier: {{ .Values.payment_name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
    tier: {{ .Values.payment_name }}
    appd-appname: {{ .Values.payment_appd }}
  name: {{ .Values.appname }}-{{ .Values.payment_name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      tier: {{ .Values.payment_name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        tier: {{ .Values.payment_name }}
    spec:
#      serviceAccountName: no-priv
#      automountServiceAccountToken: false
#      securityContext:
#        runAsUser: 10000
#        runAsGroup: 20000
#        fsGroup: 30000
      containers:
      - name: payment
        image: {{ .Values.registry }}/payment-{{ .Values.payment_tech }}:{{ .Values.payment_version }}
        imagePullPolicy: Always
#        securityContext:
#          runAsUser: 10001
#          allowPrivilegeEscalation: false
        env:
        - name: APPD_APP_NAME
          value: {{ .Values.appname }}
        - name: APPD_TIER_NAME
          value: {{ .Values.payment_appd }}
        envFrom:
        - configMapRef:
            name: appd-config
        volumeMounts:
        - name: customization
          mountPath: /etc/customization
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
#        - name: https
#          containerPort: 443
#          protocol: TCP
        startupProbe:
          periodSeconds: 5
          failureThreshold: 40
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 4
          httpGet:
            path: /healthz
            port: http
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: customization
        configMap:
          name: customization  