apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 125m
      memory: 64Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 12Gi
    requests.storage: 40Gi
    persistentvolumeclaims: 10
    requests.nvidia.com/gpu: 0
    pods: "200"
    replicationcontrollers: "50"
    secrets: "100"
    services: "100"
    services.loadbalancers: "2"