apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component6 }}
spec:
  selector:
    matchLabels:
      name: app-load
  replicas: {{ .Values.component6_replicas }}
  template:
    metadata:
      labels:
        name: app-load
    spec:
      containers:
        - name: app-load
          image: sashaz/app-load:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

