kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.component11 }}
  labels:
    app: devminion
spec:
  replicas: {{ .Values.component11_replicas }}
  selector:
    matchLabels:
      app: devminion
  template:
    metadata:
      labels:
        app: devminion
    spec:
      containers:
        - name: {{ .Values.component11 }}-cpu
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: '90'
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 240m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: {{ .Values.component11 }}-mem
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: memory
            - name: MEMORY_NUM
              value: '910'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
