apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component9 }}
spec:
  selector:
    matchLabels:
      name: player-action-services
  replicas: {{ .Values.component9_replicas }}
  template:
    metadata:
      labels:
        name: player-action-services
        tier-name: player-action-services-tier
        application-name: OS-App
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: player-action-services
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: player-action-services
spec:
  selector:
    name: player-action-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
