apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "100"
    requests.cpu: "6"
    limits.cpu: "6"
    requests.memory: 30G
    limits.memory: 30G
    persistentvolumeclaims: 10
    requests.storage: 100G
