apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-config
  namespace: {{ .Release.Namespace }}
data:
  ACCOUNT_NAME: "{{ .Values.appd_account_name }}"
  CONTROLLER_HOST: "{{ .Values.appd_controller_hostname }}"
  CONTROLLER_PORT: "443"
  CONTROLLER_SSL: "{{ .Values.appd_controller_ssl }}"
  ACCESS_KEY: "{{ .Values.appd_controller_key }}"
  APP_NAME: "{{ .Values.appname }}"
  {{- if .Values.proxy_host }}
  PROXY_HOST: "{{ .Values.proxy_host }}"
  {{- end }}
  {{- if .Values.proxy_port }}
  PROXY_PORT: "{{ .Values.proxy_port }}"
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appd-dbagent
  name: appd-dbagent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appd-dbagent
  strategy: {}
  template:
    metadata:
      labels:
        app: appd-dbagent
    spec:
      #serviceAccountName: no-priv
      #automountServiceAccountToken: false
#      securityContext:
#        runAsUser: 10000
#        runAsGroup: 20000
#        fsGroup: 30000
      containers:
      - name: appd-dbagent
        image: {{ .Values.registry }}/appd-dbagent:{{ .Values.dbagent_version }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: appd-config
#        securityContext:
#          runAsUser: 10001
#          allowPrivilegeEscalation: false
#        ports:
#        - name: http
#          containerPort: 80
#          protocol: TCP
#        - name: https
#          containerPort: 443
#          protocol: TCP
#        startupProbe:
#          periodSeconds: 5
#          failureThreshold: 40
#          httpGet:
#            path: /healthz
#            port: http
#        livenessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 2
#          failureThreshold: 4
#          httpGet:
#            path: /healthz
#            port: http
#        resources:
#          requests:
#            cpu: 500m
#            memory: 64Mi
#          limits:
#            memory: 64Mi