kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-constrained
  labels:
    app: devminion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devminion
  template:
    metadata:
      labels:
        app: devminion
    spec:
      nodeSelector:
        capability: gpu
      containers:
        - name: gpu-container
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: '90'
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 240m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
