kind: Deployment
apiVersion: apps/v1
metadata:
  name: oversized
  labels:
    app: oversized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oversized
  template:
    metadata:
      labels:
        app: oversized
    spec:
      containers:
        - name: oversizedcpu
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: '10'
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 240m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: oversizedmem
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: memory
            - name: MEMORY_NUM
              value: '250'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
