apiVersion: v1
kind: Namespace
metadata:
  name: stealthwatch
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: obsrvbl
  namespace: stealthwatch
data:
  service_key: {{ .Values.stlth_service_key }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: obsrvbl
  namespace: stealthwatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: obsrvbl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: obsrvbl
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obsrvbl-ona
  namespace: stealthwatch
spec:
  selector:
    matchLabels:
      name: obsrvbl-ona
  template:
    metadata:
      labels:
        name: obsrvbl-ona
    spec:
      serviceAccountName: obsrvbl
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      containers:
        - name: ona
          image: obsrvbl/ona:4.2
          env:
            - name: OBSRVBL_HOST
              value: "https://sensor.staging.obsrvbl.com"
            - name: OBSRVBL_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: obsrvbl
                  key: service_key
            - name: OBSRVBL_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OBSRVBL_KUBERNETES_WATCHER
              value: "true"
            - name: OBSRVBL_HOSTNAME_RESOLVER
              value: "false"
            - name: OBSRVBL_NOTIFICATION_PUBLISHER
              value: "false"